name: Full build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        options:
          - development
          - production
          - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform
        run: |
          cd project-infra/envs/${{ github.event.inputs.environment }}
          echo '${{ secrets.GCP_SA_TERRAFORM }}' | tr -d '\r' > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$PWD/gcp-key.json"
          cd cloud_run
          terraform init
          terraform apply -auto-approve \
            -var="main_image=${{ vars.MAIN_IMAGE }}" \
            -var="actions_image=${{ vars.ACTION_IMAGE }}" \
            -var="project_id=${{ vars.PROJECT_ID }}" \
            -var="service_account=${{ vars.TERRAFORM_SA_NAME }}" \
            -var="env_vars={\"DATABASE\":\"${{ vars.DATABASE }}\", \"ENVIRONMENT\":\"${{ github.event.inputs.environment }}\"}"
          cd ../scheduler
          terraform init
          terraform apply -auto-approve \
            -var="default_sa=${{ vars.DEFAULT_SA }}" \
            -var="cron_scheduler_sync=0 4-21 * * *" \
            -var="cron_scheduler_complete=0 3 * * *" \
            -var="cron_scheduled_health_data=25,55 * * * *" \
            -var="project_id=${{ vars.PROJECT_ID }}"
          cd ../eventarc
          terraform init
          terraform apply -auto-approve \
            -var="location=nam5" \
            -var="cloud_run_region=us-central1" \
            -var="service_account=${{ vars.DEFAULT_SA }}" \
            -var="project_id=${{ vars.PROJECT_ID }}" \
            -var="database=${{ vars.DATABASE }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/terraform/gcp-key.json